<Project>
  <PropertyGroup>
    <Version>2.1.0</Version>
    <Company>tecertools Digital Solutions</Company>
    <Product>DELIMa Smart Launcher</Product>
    <Copyright>© 2026 tecertools Digital Solutions</Copyright>
    <NeutralLanguage>ms-MY</NeutralLanguage>
    <ApplicationIcon>$(MSBuildThisFileDirectory)icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
